#!/usr/bin/env bun
/**
 * Approval Queue consumer (RYA-166) — CLI entry.
 *
 * Scans `2. Areas/Social Media/Approval Queue/` and hands every note a human has
 * marked `status: approved` to sm-manager's `post-scheduler` skill.
 *
 * Runs under `bun` rather than inside the Electron main process on purpose: the
 * whole value is approving from Obsidian on a phone while the Mac sits closed,
 * and an in-app watcher only fires when RyanOS is open — exactly when Ryan does
 * not need it. Nothing in this file's import graph touches Electron.
 *
 *   bun apps/desktop/scripts/drain-queue.ts            # dry run (default)
 *   bun apps/desktop/scripts/drain-queue.ts --ship     # actually schedule
 *
 * Design + invariants: docs/superpowers/specs/2026-07-14-approval-queue-consumer-design.md
 */
import { spawn } from "node:child_process";
import {
	existsSync,
	mkdirSync,
	openSync,
	readdirSync,
	readFileSync,
	writeFileSync,
} from "node:fs";
import { homedir } from "node:os";
import { join } from "node:path";
import {
	type DrainDeps,
	drain,
	formatReport,
	type ShipTarget,
} from "../src/main/lib/approval-queue/ship";
import { vaultRoot } from "../src/main/lib/orchestrator/vault";

const QUEUE_DIR = join(vaultRoot(), "2. Areas/Social Media/Approval Queue");
const ADE_HOME = process.env.ADE_HOME_DIR || join(homedir(), ".ade");
const LOG_DIR = join(ADE_HOME, "orchestrator-logs");

/**
 * Find the seeded brain that owns `post-scheduler`, by capability rather than by
 * id. Agent ids are regenerated by a re-seed (`mv ~/.ade`), so a hardcoded UUID
 * would rot silently — and a queue that stops draining without saying why is the
 * failure mode this whole issue exists to fix.
 */
function resolveSchedulerBrain(): string | null {
	const agentsDir = join(ADE_HOME, "agents");
	if (!existsSync(agentsDir)) return null;
	for (const id of readdirSync(agentsDir)) {
		const dir = join(agentsDir, id);
		if (existsSync(join(dir, "skills", "post-scheduler"))) return dir;
	}
	return null;
}

/**
 * Quote a value for `/bin/sh`.
 *
 * NOT `JSON.stringify`. This command runs through a shell (`shell: true`), and
 * JSON.stringify yields a DOUBLE-quoted string — inside which sh still expands
 * backticks and `$`. The dispatch prompt is full of backticks (`status: approved`),
 * so double-quoting silently executed each one as a command and substituted its
 * empty output: the agent received "by setting  in its frontmatter", with every
 * load-bearing instruction deleted. Caught by running it against a stub `claude`;
 * a unit test on the command string would have looked fine.
 *
 * Single quotes are the only sh construct that suppresses everything; the dance
 * below is the standard way to embed a literal single quote inside them.
 */
function shq(s: string): string {
	return `'${s.replace(/'/g, `'\\''`)}'`;
}

/** Mirrors buildAgentLaunchCommand() in src/main/lib/agent-launch.ts — the app
 *  builds this from the DB, which a standalone script has no business opening. */
function buildCommand(brain: string, prompt: string): string {
	return (
		"CLAUDE_CODE_ADDITIONAL_DIRECTORIES_CLAUDE_MD=1 claude " +
		"--model 'claude-opus-4-8[1m]' " +
		`--settings ${shq(join(brain, "settings.json"))} ` +
		`--append-system-prompt-file ${shq(join(brain, "persona.txt"))} ` +
		`--add-dir ${shq(join(brain, "context"))} ` +
		`--mcp-config ${shq(join(brain, "mcp.json"))} --strict-mcp-config ` +
		`--dangerously-skip-permissions -p ${shq(prompt)}`
	);
}

/**
 * The dispatch prompt.
 *
 * Two things it must get exactly right:
 *  - post-scheduler blocks on "WAIT for the operator". That gate is already
 *    satisfied — by the human who typed `approved` into the note — so the prompt
 *    says so explicitly. Otherwise the agent waits forever for a session that
 *    does not exist (which is RYA-167 in a different costume).
 *  - The note is currently claimed (`scheduling`). The agent MUST move it off
 *    that value, or the next run parks it as needs-review.
 */
function buildPrompt(t: ShipTarget): string {
	return [
		"Use your post-scheduler skill to schedule the already-approved post in this note:",
		t.file,
		"",
		"The operator (Ryan) ALREADY approved this post by setting `status: approved` in its",
		"frontmatter. That edit IS the approval gate for this post. Treat post-scheduler's",
		'"WAIT for the operator" step as satisfied. Do NOT ask for approval and do NOT wait',
		"for a reply: you are running headless and there is no session to answer you.",
		"",
		`Platforms: ${t.targets.join(", ")}`,
		`Media: ${t.media ?? "(none attached)"}`,
		"",
		"Still run the Step 2 pre-publish check. If it fails, do NOT publish. Set",
		"`status: needs-review` in the note plus a `needs_review_reason:` line, and stop.",
		"",
		"On a successful schedule, set in the note's frontmatter:",
		"  status: scheduled",
		"  blotato_post_id: <the id Blotato returned>",
		"  scheduled_time: <the ISO time Blotato returned>",
		"",
		"The note currently reads `status: scheduling` — a claim taken by drain-queue so a",
		"concurrent run cannot double-post it. Before you exit it MUST read either",
		"`scheduled` or `needs-review`. Never leave it at `scheduling`.",
	].join("\n");
}

function main(): void {
	const ship = process.argv.includes("--ship");

	if (!existsSync(QUEUE_DIR)) {
		console.log(`Approval Queue not found at ${QUEUE_DIR} — nothing to do.`);
		return;
	}

	const brain = resolveSchedulerBrain();
	if (ship && !brain) {
		console.error(
			"No seeded agent owns the post-scheduler skill, so there is nothing to ship with.\n" +
				`Looked under ${join(ADE_HOME, "agents")}/*/skills/post-scheduler.\n` +
				"Re-seed RyanOS, or run without --ship to inspect the queue.",
		);
		process.exitCode = 1;
		return;
	}

	const deps: DrainDeps = {
		listNotes: () =>
			readdirSync(QUEUE_DIR)
				.filter((f) => f.endsWith(".md"))
				.sort()
				.map((f) => join(QUEUE_DIR, f)),
		read: (p) => readFileSync(p, "utf8"),
		write: (p, c) => writeFileSync(p, c, "utf8"),
		dispatch: (t) => {
			// Detached + unref'd, mirroring the orchestrator's spawnHeadless: the
			// shipper must outlive this short-lived cron process.
			let stdio: "ignore" | ["ignore", number, number] = "ignore";
			try {
				mkdirSync(LOG_DIR, { recursive: true });
				const fd = openSync(join(LOG_DIR, "drain-queue-dispatch.log"), "a");
				stdio = ["ignore", fd, fd];
			} catch {
				// logging must never break a dispatch
			}
			const child = spawn(buildCommand(brain as string, buildPrompt(t)), {
				shell: true,
				cwd: vaultRoot(),
				detached: true,
				stdio,
			});
			child.unref();
		},
		now: () => Date.now(),
	};

	const report = drain(deps, { ship });
	console.log(formatReport(report, { ship, at: new Date().toISOString() }));

	if (!ship && report.shippable.length) {
		console.log("\nRe-run with --ship to schedule the above.");
	}
	if (report.errors.length) process.exitCode = 1;
}

main();
