import { execFileSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import { join } from "node:path";

export type BuildInfo = {
	version: string;
	commit: string;
	commitFull: string;
	branch: string;
	buildDate: string;
	tag: string;
};

const DESKTOP_DIR = join(import.meta.dir, "..");
const OUT_PATH = join(DESKTOP_DIR, "src/shared/build-info.generated.ts");

function git(args: string[]): string {
	try {
		return execFileSync("git", args, {
			cwd: DESKTOP_DIR,
			encoding: "utf8",
		}).trim();
	} catch {
		return "";
	}
}

export function collectBuildInfo(): BuildInfo {
	const pkg = require(join(DESKTOP_DIR, "package.json")) as { version: string };
	const commitFull = git(["rev-parse", "HEAD"]) || "dev";
	const commit = git(["rev-parse", "--short", "HEAD"]) || "dev";
	const branch = git(["rev-parse", "--abbrev-ref", "HEAD"]) || "dev";
	const tag = git(["describe", "--tags", "--exact-match"]); // "" when not exactly on a tag
	const buildDate = new Date().toISOString().slice(0, 10);
	return { version: pkg.version, commit, commitFull, branch, buildDate, tag };
}

export function renderBuildInfoModule(info: BuildInfo): string {
	return `// machine-generated by scripts/gen-build-info.ts — do not edit by hand.
export type BuildInfo = {
	version: string;
	commit: string;
	commitFull: string;
	branch: string;
	buildDate: string;
	tag: string;
};

// Typed as BuildInfo (not \`as const\`) so fields stay \`string\` — otherwise the
// literal commit value would leak into the type and break commit comparisons.
export const BUILD_INFO: BuildInfo = {
	version: ${JSON.stringify(info.version)},
	commit: ${JSON.stringify(info.commit)},
	commitFull: ${JSON.stringify(info.commitFull)},
	branch: ${JSON.stringify(info.branch)},
	buildDate: ${JSON.stringify(info.buildDate)},
	tag: ${JSON.stringify(info.tag)},
};
`;
}

// Run directly (bun scripts/gen-build-info.ts) → write the module.
if (import.meta.main) {
	const info = collectBuildInfo();
	writeFileSync(OUT_PATH, renderBuildInfoModule(info), "utf8");
	console.info(
		`[gen-build-info] ${info.version} ${info.commit} (${info.branch}) ${info.buildDate}`,
	);
}
