// machine-generated by scripts/gen-build-info.ts — safe dev defaults committed;
// overwritten with real git values before every dev/build/typecheck.
export type BuildInfo = {
	version: string;
	commit: string;
	commitFull: string;
	branch: string;
	buildDate: string;
	tag: string;
};

// Typed as BuildInfo (not `as const`) so fields stay `string` — otherwise the
// literal commit value would leak into the type and break commit comparisons.
export const BUILD_INFO: BuildInfo = {
	version: "0.2.0",
	commit: "dev",
	commitFull: "dev",
	branch: "dev",
	buildDate: "",
	tag: "",
};
