// machine-generated by scripts/gen-build-info.ts — safe dev defaults committed;
// overwritten with real git values before every dev/build/typecheck.
export const BUILD_INFO = {
	version: "0.2.0",
	commit: "dev",
	commitFull: "dev",
	branch: "dev",
	buildDate: "",
	tag: "",
} as const;

export type BuildInfo = {
	version: string;
	commit: string;
	commitFull: string;
	branch: string;
	buildDate: string;
	tag: string;
};
