// machine-generated by scripts/gen-build-info.ts — do not edit by hand.
export type BuildInfo = {
	version: string;
	commit: string;
	commitFull: string;
	branch: string;
	buildDate: string;
	tag: string;
};

// Typed as BuildInfo (not `as const`) so fields stay `string` — otherwise the
// literal commit value would leak into the type and break commit comparisons.
export const BUILD_INFO: BuildInfo = {
	version: "0.2.0",
	commit: "a1dc7da",
	commitFull: "a1dc7da17060d81ff95091d01d224b7ffee97e61",
	branch: "main",
	buildDate: "2026-08-09",
	tag: "",
};
